id: AE202F44E
title: 'The Crystal Stairway: A Prayer of Aspiration to Cross Over to the Copper-Coloured
  Mountain of Glory in the South West'
type: translation
pechas:
- I64456E96
- I492D10A9
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:49:02.071002
  last_modified_at: 2023-01-04 12:49:02.071017
  collections:
  - Khangsar Tenpé Wangchuk
  - Works of Tibetan Masters
alignment_to_base:
  I64456E96/33BC: F9D5
  I492D10A9/7640: F9D5
